source 'https://rubygems.org'

gem 'rails', '3.2.2'
gem 'sqlite3', '1.3.5'

gem 'jquery-rails', '2.0.1'

group :development do
  gem "nifty-generators"
end

group :test, :development do
  gem 'cucumber-rails', '1.3.0'
  gem 'jasmine', '1.1.2'
  gem 'rspec-rails', '2.9.0'
end

group :test do
  gem "capybara", '1.1.2'
  gem 'database_cleaner', '0.7.1'
end

gem "mocha", :group => :test